# Generated by Django 4.2.11 on 2026-03-27 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_objetivosemana_misionhoy_keepnota'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(default='⭐', max_length=50)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RegistroRueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(default=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.categoriarueda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_rueda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['categoria__orden'],
                'unique_together': {('user', 'categoria')},
            },
        ),
    ]
