# Generated by Django 4.2.11 on 2026-03-27 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_categoriarueda_registrorueda'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('quadrant', models.CharField(choices=[('do', 'Do (Urgent & Important)'), ('schedule', 'Schedule (Not Urgent & Important)'), ('delegate', 'Delegate (Urgent & Not Important)'), ('eliminate', 'Eliminate (Not Urgent & Not Important)')], max_length=20)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
