# Generated by Django 4.2.11 on 2026-03-28 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_matrixitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbantask',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_vencimiento', models.DateField()),
                ('pagado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_vencimiento'],
            },
        ),
    ]
