# Generated by Django 4.2.11 on 2026-05-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordatorio',
            name='tomado',
            field=models.BooleanField(default=False),
        ),
    ]
