# Generated by Django 4.2.11 on 2026-05-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_seed_categorias_rueda'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kanbantask',
            name='uuid',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AlterField(
            model_name='recordatorio',
            name='categoria',
            field=models.CharField(choices=[('Medicamento', 'Medicamento'), ('Cumpleaños', 'Cumpleaños'), ('HoraOro', 'Hora de Oro'), ('Equipo', 'Equipo'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
