# Generated by Django 4.2.11 on 2026-06-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_delegation_expires_at_kanbantask_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='misionhoy',
            name='texto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
