# Generated by Django 4.2.11 on 2026-06-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_misionhoy_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeblock',
            name='estado',
            field=models.CharField(choices=[('pending', 'Pending'), ('doing', 'Doing'), ('done', 'Done')], default='pending', max_length=10),
        ),
    ]
