# Generated by Django 4.2.11 on 2026-06-18 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_misionhoy_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('aprobada', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_anuales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_impacto', models.CharField(choices=[('estructural', 'Estructural (Alta Saturación)'), ('estrategico_critico', 'Estratégico Crítico'), ('de_prioridad', 'De Prioridad (Desorden Generalizado)')], max_length=30)),
                ('situacion_clara', models.TextField()),
                ('explicacion_impacto', models.TextField()),
                ('propuesta_ajuste', models.TextField()),
                ('fase_detectada', models.CharField(blank=True, default='', max_length=50)),
                ('respondida', models.BooleanField(default=False)),
                ('decision_usuario', models.CharField(blank=True, choices=[('aplicar', 'Aplicar Ajuste Ahora'), ('revisar', 'Revisar Después'), ('mantener', 'Mantener Planificación Actual'), ('ignorado', 'Ignorado')], default='', max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('completado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('meta_anual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos_mensuales', to='dashboard.metaanual')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_mensuales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-meta_anual', 'mes'],
            },
        ),
    ]
