# Generated by Django 4.2.11 on 2026-06-16 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_change_estado_to_charfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('anual', 'Anual'), ('mensual', 'Mensual'), ('semanal', 'Semanal'), ('diaria', 'Diaria')], max_length=10)),
                ('texto', models.CharField(max_length=500)),
                ('completada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tipo', 'created_at'],
            },
        ),
    ]
