# Generated by Django 4.2.11 on 2026-06-18 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_metaanual_propuestaia_objetivomensual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voz_genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='femenino', max_length=10)),
                ('estilo_comunicacion', models.CharField(choices=[('suave', 'Suave'), ('directo', 'Directo / Estructurado')], default='suave', max_length=10)),
                ('nivel_exigencia', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', max_length=5)),
                ('frecuencia_intervenciones', models.IntegerField(default=24, help_text='Horas entre intervenciones permitidas')),
                ('canales_interaccion', models.JSONField(blank=True, default=list, help_text='Canales habilitados: ["notificacion", "simulacion_llamada", "whatsapp_simulado", "buzon_ia"]')),
                ('ventana_inicio', models.TimeField(default='07:00', help_text='Inicio de ventana de intervención')),
                ('ventana_fin', models.TimeField(default='22:00', help_text='Fin de ventana de intervención')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Usuario',
                'verbose_name_plural': 'Configuraciones de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Activacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tradicional', 'Recordatorio Tradicional'), ('simulada', 'Activación Simulada (Llamada/WhatsApp)'), ('con_intencion', 'Activación con Intención (Propósito)'), ('adaptativa', 'Activación Adaptativa (IA)')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('vista', 'Vista'), ('respondida', 'Respondida'), ('ignorada', 'Ignorada'), ('fallida', 'Fallida')], default='pendiente', max_length=15)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('mensaje_intencion', models.TextField(blank=True, default='', help_text='Mensaje que vincula con propósito mayor (para activaciones con intención)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos extras: tarea_id, bloque_id, url_simulacion, etc.')),
                ('ventana_programada', models.DateTimeField(blank=True, help_text='Momento óptimo calculado por IA para enviar', null=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('respondida_en', models.DateTimeField(blank=True, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
    ]
