# Generated by Django 4.2.11 on 2026-06-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_configuracionusuario_activacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuestaia',
            name='resultado_json',
            field=models.JSONField(blank=True, default=dict, help_text='Payload completo de la respuesta del motor de IA según especificación del sistema'),
        ),
        migrations.AlterField(
            model_name='propuestaia',
            name='tipo_impacto',
            field=models.CharField(choices=[('estructural', 'ESTRUCTURAL_SATURACIÓN'), ('estrategico_critico', 'ESTRATÉGICO_CRÍTICO'), ('de_prioridad', 'PRIORIDAD_REORGANIZACIÓN')], max_length=30),
        ),
    ]
