# Generated by Django 4.2.11 on 2026-06-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_propuestaia_resultado_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionusuario',
            name='avatar_index',
            field=models.IntegerField(default=0, help_text='0=sin selección, 1-6=avatar seleccionado en onboarding'),
        ),
        migrations.AddField(
            model_name='configuracionusuario',
            name='onboarding_completado',
            field=models.BooleanField(default=False, help_text='Indica si el usuario completó el flujo de onboarding'),
        ),
    ]
