# Generated by Django 4.2.11 on 2026-06-18 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_configuracionusuario_avatar_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionusuario',
            name='ultimo_ingreso',
            field=models.DateTimeField(blank=True, help_text='Timestamp del último acceso al hub post-onboarding', null=True),
        ),
        migrations.AddField(
            model_name='configuracionusuario',
            name='video_inicial_visto',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ya vio el video introductorio post-onboarding'),
        ),
        migrations.CreateModel(
            name='InteraccionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_index=True, help_text='Tipo de evento: video_view, tutorial_click, guided_tour_step, config_change, etc.', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales: tiempo_visto, origen, categoria, paso, etc.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interacción de Usuario',
                'verbose_name_plural': 'Interacciones de Usuarios',
                'ordering': ['-creado'],
            },
        ),
    ]
