# Generated by Django 4.2.11 on 2026-06-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_configuracionusuario_ultimo_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionusuario',
            name='conteo_ingresos_hub',
            field=models.IntegerField(default=0, help_text='Número de veces que el usuario ha ingresado al hub post-onboarding'),
        ),
    ]
