# Generated by Django 4.2.11 on 2026-06-18 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_configuracionusuario_conteo_ingresos_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrorueda',
            name='comentario',
            field=models.TextField(blank=True, default='', help_text='Comentario opcional del usuario sobre esta área'),
        ),
        migrations.CreateModel(
            name='DiagnosticoRueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_general', models.FloatField(default=0, help_text='Promedio general de todos los puntajes')),
                ('nivel_equilibrio', models.CharField(default='medio', help_text='Crítico | Bajo | Medio | Bueno | Excelente', max_length=20)),
                ('pico_alto', models.CharField(blank=True, default='', max_length=100)),
                ('pico_bajo', models.CharField(blank=True, default='', max_length=100)),
                ('foco_1', models.CharField(blank=True, default='', help_text='Nombre del área foco 1', max_length=100)),
                ('foco_2', models.CharField(blank=True, default='', help_text='Nombre del área foco 2', max_length=100)),
                ('foco_3', models.CharField(blank=True, default='', help_text='Nombre del área foco 3', max_length=100)),
                ('justificacion_focos', models.TextField(blank=True, default='', help_text='Justificación estratégica de los 3 focos seleccionados')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico_rueda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnóstico de Rueda',
                'verbose_name_plural': 'Diagnósticos de Rueda',
            },
        ),
        migrations.CreateModel(
            name='AccionSugerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_foco', models.CharField(help_text='Nombre del área foco a la que pertenece', max_length=100)),
                ('texto', models.TextField(help_text='Descripción de la acción sugerida')),
                ('enviada_kanban', models.BooleanField(default=False, help_text='Si ya fue enviada al Kanban Backlog')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_sugeridas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acción Sugerida',
                'verbose_name_plural': 'Acciones Sugeridas',
                'ordering': ['-creado'],
            },
        ),
    ]
