# Generated by Django 4.2.11 on 2026-06-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_user_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
