# Generated by Django 4.2.11 on 2026-06-18 21:06

from django.db import migrations

SPEC_AREAS = [
    {'nombre': 'Trabajo', 'icono': '💼', 'orden': 1},
    {'nombre': 'Dinero', 'icono': '💰', 'orden': 2},
    {'nombre': 'Salud', 'icono': '💪', 'orden': 3},
    {'nombre': 'Pareja', 'icono': '❤️', 'orden': 4},
    {'nombre': 'Familia', 'icono': '👨‍👩‍👧‍👦', 'orden': 5},
    {'nombre': 'Espiritualidad', 'icono': '🕊️', 'orden': 6},
    {'nombre': 'Diversión', 'icono': '🎮', 'orden': 7},
    {'nombre': 'Entorno', 'icono': '🏠', 'orden': 8},
    {'nombre': 'Desarrollo', 'icono': '🌱', 'orden': 9},
    {'nombre': 'Contribución', 'icono': '🤝', 'orden': 10},
]

def seed_categorias(apps, schema_editor):
    CategoriaRueda = apps.get_model('dashboard', 'CategoriaRueda')
    RegistroRueda = apps.get_model('dashboard', 'RegistroRueda')
    # Delete old registros that reference old categories
    RegistroRueda.objects.all().delete()
    # Delete old categories
    CategoriaRueda.objects.all().delete()
    # Insert new categories
    for cat in SPEC_AREAS:
        CategoriaRueda.objects.create(**cat)

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_registrorueda_comentario_diagnosticorueda_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_categorias),
    ]
