# Generated by Django 4.2.11 on 2026-06-22 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_seed_10_categorias_rueda'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizEisenhower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INCOMPLETO', 'Incompleto'), ('COMPLETADO', 'Completado')], default='INCOMPLETO', max_length=20)),
                ('video_watched', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matriz_eisenhower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matriz Eisenhower',
                'verbose_name_plural': 'Matriz Eisenhower',
            },
        ),
    ]
