# Generated by Django 4.2.11 on 2026-06-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_merge_0020_user_onboarding_data_0021_seed_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisuggestion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='granmetaanual',
            name='user',
        ),
        migrations.RemoveField(
            model_name='metausuario',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='locked_until',
        ),
        migrations.RemoveField(
            model_name='user',
            name='onboarding_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='onboarding_data',
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='estado',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='AdaptiveThreshold',
        ),
        migrations.DeleteModel(
            name='AISuggestion',
        ),
        migrations.DeleteModel(
            name='GranMetaAnual',
        ),
        migrations.DeleteModel(
            name='MetaUsuario',
        ),
    ]
