# Generated by Django 4.2.11 on 2026-06-20 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_aisuggestion_user_remove_granmetaanual_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_start_month', models.IntegerField(help_text='Mes de inicio del ciclo (1-12)')),
                ('cycle_start_year', models.IntegerField(help_text='Año de inicio del ciclo')),
                ('status', models.CharField(choices=[('PROPUESTA', 'Propuesta'), ('APROBADA', 'Aprobada'), ('PENDIENTE_REVISION', 'Pendiente de Revisión')], default='PROPUESTA', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('annual_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to='dashboard.metaanual')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_order', models.IntegerField(help_text='Posición en el ciclo personalizado (1-12)')),
                ('calendar_month', models.IntegerField(help_text='Mes real del calendario gregoriano (1-12)')),
                ('calendar_year', models.IntegerField(help_text='Año real del calendario gregoriano')),
                ('monthly_goal_text', models.CharField(help_text='Frase de la meta mensual', max_length=500)),
                ('brief_explanation', models.TextField(blank=True, default='', help_text='Justificación de 1-2 líneas')),
                ('annual_goal_relation', models.TextField(blank=True, default='', help_text='Conexión con la meta anual')),
                ('complexity_level', models.CharField(choices=[('BASE', 'Base'), ('EJECUCION', 'Ejecución'), ('CONSOLIDACION', 'Consolidación'), ('CIERRE', 'Cierre')], default='BASE', max_length=15)),
                ('status', models.CharField(choices=[('PROPUESTA', 'Propuesta'), ('EDITADA', 'Editada'), ('APROBADA', 'Aprobada'), ('PENDIENTE', 'Pendiente')], default='PROPUESTA', max_length=15)),
                ('edited_by_user', models.BooleanField(default=False, help_text='Flag de auditoría para métricas de IA')),
                ('version', models.IntegerField(default=1, help_text='Contador de control de cambios')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='dashboard.monthlyplan')),
            ],
            options={
                'ordering': ['month_order'],
                'unique_together': {('plan', 'month_order')},
            },
        ),
    ]
