# Generated by Django 4.2.11 on 2026-06-20 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_monthly_plans_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizLearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INCOMPLETO', 'Incompleto'), ('COMPLETADO', 'Completado')], default='INCOMPLETO', max_length=15)),
                ('video_watched', models.BooleanField(default=False)),
                ('practice_score', models.IntegerField(default=0, help_text='Número de aciertos en la trivia')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matriz_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
